# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-11 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watched',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.IntegerField()),
                ('time_watched', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Video')),
            ],
            options={
                'verbose_name_plural': 'Watcheds',
                'verbose_name': 'Watched',
            },
        ),
        migrations.AddField(
            model_name='video',
            name='users',
            field=models.ManyToManyField(through='api.Watched', to='api.User'),
        ),
    ]
