# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-17 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20170117_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thesaurus_terms',
            field=models.CharField(max_length=150),
        ),
    ]
