# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-25 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_enrichment'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoContentScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=3, max_digits=6)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Term')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Video')),
            ],
            options={
                'verbose_name_plural': 'VideoContentScores',
                'verbose_name': 'VideoContentScore',
            },
        ),
        migrations.AddField(
            model_name='video',
            name='scores',
            field=models.ManyToManyField(through='api.VideoContentScore', to='api.Term'),
        ),
    ]
