# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-25 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20170125_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoInteractions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_action_performed', models.DateTimeField(auto_now=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Action')),
                ('watched', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Watched')),
            ],
            options={
                'verbose_name': 'VideoInteractions',
                'verbose_name_plural': 'VideoInteractionss',
            },
        ),
        migrations.AddField(
            model_name='watched',
            name='interactions',
            field=models.ManyToManyField(through='api.VideoInteractions', to='api.Action'),
        ),
    ]
