# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-26 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20170125_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='videointeractions',
            name='computed',
            field=models.BooleanField(default=0),
        ),
    ]
