# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-29 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20170228_1459'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videoenrichments',
            options={'verbose_name': 'VideoEnrichments', 'verbose_name_plural': 'VideosEnrichments'},
        ),
        migrations.AlterModelOptions(
            name='videointeractions',
            options={'verbose_name': 'VideoInteractions', 'verbose_name_plural': 'VideosInteractions'},
        ),
        migrations.AlterModelOptions(
            name='videowatched',
            options={'verbose_name': 'VideoWatched', 'verbose_name_plural': 'VideosWatched'},
        ),
        migrations.RenameField(
            model_name='video',
            old_name='enrichements',
            new_name='enrichments',
        ),
    ]
