# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-16 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20180312_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videoenrichments',
            old_name='height',
            new_name='x',
        ),
        migrations.RenameField(
            model_name='videoenrichments',
            old_name='width',
            new_name='y',
        ),
        migrations.RemoveField(
            model_name='enrichment',
            name='dbpediaURL',
        ),
        migrations.RemoveField(
            model_name='enrichment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='enrichment',
            name='enrichment_class',
        ),
        migrations.RemoveField(
            model_name='enrichment',
            name='longName',
        ),
        migrations.RemoveField(
            model_name='enrichment',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='enrichment',
            name='wikipediaURL',
        ),
        migrations.RemoveField(
            model_name='videoenrichments',
            name='time',
        ),
        migrations.RemoveField(
            model_name='videoenrichments',
            name='x_min',
        ),
        migrations.RemoveField(
            model_name='videoenrichments',
            name='y_min',
        ),
        migrations.AddField(
            model_name='enrichment',
            name='name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='enrichment',
            name='overlay_text_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='enrichment',
            name='overlay_title',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='enrichment',
            name='title',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='videoenrichments',
            name='end_time',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='videoenrichments',
            name='project_id',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='videoenrichments',
            name='start_time',
            field=models.IntegerField(default=0),
        ),
    ]
