# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-28 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20180316_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrichment',
            name='dbpediaURL',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='enrichment',
            name='enrichment_class',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='enrichment',
            name='thumbnail',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='enrichment',
            name='wikipediaURL',
            field=models.CharField(default='', max_length=150),
        ),
    ]
