# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-27 10:53
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20180328_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoenrichments',
            name='marker',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
        ),
    ]
