version: '3'

volumes:
  static-files:


services:
  db:
    image: postgres
    volumes:
      - /opt/sptool/psql:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    env_file:
      - ./config/.env

  webserver:
    build:
      context: .
      dockerfile: services/webserver/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - webapp
    volumes:
      - static-files:/srv/static-files
    env_file:
      - ./config/.env

  webapp:
    build:
      context: webapp
    volumes:
      - ./webapp/sptool:/srv/sptool
      - static-files:/srv/static-files
    expose:
      - "8000"
    depends_on:
      - db
    env_file:
      - ./config/.env
