version: '3'

volumes:
  static-files:
  certs:
  certs-data:


services:
  db:
    image: postgres:10
    volumes:
      - /opt/sptool/psql:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    env_file:
      - ./config/.env

  webserver:
    build:
      context: .
      dockerfile: services/webserver/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - webapp
    volumes:
      - certs:/etc/letsencrypt
      - certs-data:/data/letsencrypt
      - static-files:/srv/static-files
      - ./media_files:/srv/media_files
    env_file:
      - ./config/.env

  webapp:
    build:
      context: webapp
    volumes:
      - ./webapp/sptool:/srv/sptool
      - static-files:/srv/static-files
      - ./data_files:/srv/sptool/api/management/commands/data_files
    expose:
      - "8000"
    depends_on:
      - db
    env_file:
      - ./config/.env
