# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-08 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_education_occupation'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Age')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Country')),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Education')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Gender')),
                ('occupation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Occupation')),
            ],
            options={
                'verbose_name_plural': 'Users',
                'verbose_name': 'User',
            },
        ),
    ]
