# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-11 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20161111_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('euscreen', models.CharField(max_length=50, unique=True)),
                ('genre', models.CharField(max_length=50)),
                ('topic', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('geographical_coverage', models.CharField(max_length=50)),
                ('thesaurus_terms', models.CharField(max_length=50)),
                ('summary', models.TextField()),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
        ),
    ]
