# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-18 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Terms',
                'verbose_name': 'Term',
            },
        ),
    ]
