# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-26 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20170126_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoEnrichments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField()),
                ('height', models.DecimalField(decimal_places=2, max_digits=6)),
                ('width', models.DecimalField(decimal_places=2, max_digits=6)),
                ('x_min', models.DecimalField(decimal_places=2, max_digits=6)),
                ('y_min', models.DecimalField(decimal_places=2, max_digits=6)),
                ('enrichment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Enrichment')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Video')),
            ],
            options={
                'verbose_name_plural': 'VideoEnrichmentss',
                'verbose_name': 'VideoEnrichments',
            },
        ),
        migrations.AddField(
            model_name='video',
            name='enrichements',
            field=models.ManyToManyField(through='api.VideoEnrichments', to='api.Enrichment'),
        ),
    ]
