# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-17 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20170126_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='long_name',
            field=models.CharField(default='TBA', max_length=150),
        ),
    ]
