# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-22 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_term_long_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrichment',
            name='thumbnail',
            field=models.CharField(max_length=250),
        ),
    ]
