# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-28 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_video_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='videointeractions',
            name='content_id',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='videointeractions',
            name='explicit_rf',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='videointeractions',
            name='video_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='videointeractions',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
